from __future__ import annotations

import json
import subprocess
from pathlib import Path

from common.artifact_manifest import validate_manifest_payload


ROOT = Path(__file__).resolve().parents[2]
FIGURE_DIR = ROOT / "figures" / "current"
SNIPPET = ROOT / "docs" / "manuscript" / "generated" / "theorem_extension_appendix_figures.tex"


EXPECTED_FIGURES = {
    "fig_theorem_angular_kl_bound": "S1",
    "fig_theorem_dynamic_budget_barrier": "S3",
    "fig_theorem_boosted_radiation_orbit": "G2",
    "fig_theorem_slope_degeneracy": "G5",
    "fig_theorem_visibility_cancellation": "B4",
}


def _load_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def test_theorem_extension_asset_check_mode_passes() -> None:
    result = subprocess.run(
        [
            "venv/bin/python",
            "scripts/generate_theorem_extension_assets.py",
            "--check",
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    assert result.returncode == 0, result.stdout + result.stderr


def test_theorem_appendix_figures_are_manifest_backed_and_appendix_only() -> None:
    assert SNIPPET.exists()
    snippet_text = SNIPPET.read_text(encoding="utf-8")
    assert "Generated by scripts/generate_theorem_extension_assets.py" in snippet_text

    for stem, theorem_id in EXPECTED_FIGURES.items():
        figure_path = FIGURE_DIR / f"{stem}.png"
        source_path = FIGURE_DIR / f"{stem}.source.json"
        manifest_path = FIGURE_DIR / f"{stem}.manifest.json"

        assert figure_path.exists(), figure_path
        assert figure_path.read_bytes().startswith(b"\x89PNG\r\n\x1a\n")
        assert source_path.exists(), source_path
        assert manifest_path.exists(), manifest_path

        source = _load_json(source_path)
        manifest = _load_json(manifest_path)
        assert source["theorem_id"] == theorem_id
        assert source["source_input_mode"] == "synthetic_manufactured"
        assert source["claim_tier"] == "diagnostic_only"
        assert source["allowed_use"] == "paper_appendix"
        assert source["artifact_mode"] == "paper_appendix_conditioned"
        assert source["transfer_source"] == "none"
        assert source["source_json_path"] == source_path.relative_to(ROOT).as_posix()
        assert source["manifest_path"] == manifest_path.relative_to(ROOT).as_posix()
        assert source["artifact_path"] == figure_path.relative_to(ROOT).as_posix()
        assert "forbidden_use" in source
        assert "family" in " ".join(source["forbidden_use"]).lower()

        assert validate_manifest_payload(
            manifest,
            manifest_path=manifest_path,
            expected_artifact_path=figure_path.relative_to(ROOT).as_posix(),
        ) == ()
        assert manifest["owner"] == source["owner"]
        assert manifest["theorem_id"] == theorem_id
        assert manifest["claim_tier"] == "diagnostic_only"
        assert manifest["artifact_mode"] == "paper_appendix_conditioned"
        assert manifest["allowed_use"] == "paper_appendix"
        assert manifest["transfer_source"] == "none"
        assert manifest["source_json_path"] == source_path.relative_to(ROOT).as_posix()
        assert manifest["statistics_definitions"]["source_input_mode"] == "synthetic_manufactured"
        assert manifest["null_mock_status"] == "synthetic_manufactured_only"
        assert manifest["covariance_status"] == "synthetic_manufactured_only"
        assert manifest["production_status"] == "diagnostic_only"
        assert manifest["native_solver_result"] is False
        assert manifest["family_identification"] is False
        assert manifest["required_gates"]
        assert manifest["failed_gates"]
        assert "not native solver validation" in " ".join(manifest["caveats"]).lower()
        assert "not geometry or family identification" in " ".join(manifest["caveats"]).lower()

        include_target = f"current/{stem}"
        assert include_target in snippet_text
        assert f"fig:theorem-{stem.removeprefix('fig_theorem_').replace('_', '-')}" in snippet_text


def test_theorem_appendix_snippet_contains_only_appendix_conditioned_assets() -> None:
    text = SNIPPET.read_text(encoding="utf-8")
    assert "paper-main" not in text.lower()
    assert "native solver validation" in text
    assert "family identification" in text
    assert "MIO certificate" in text
    for stem in EXPECTED_FIGURES:
        assert f"\\includegraphics[width=0.92\\textwidth]{{current/{stem}}}" in text
