"""BASS background surfaces.

VER2 uses the canonical algebra/geometry/IC/evolution surfaces in this package
as the implementation anchor for background-side physics. The older reduced
`einstein_bianchi` path remains available for compatibility, but package-level
exports are now lazy so `bass.background` no longer pulls `bass.tilt` during
module initialization.
"""

from importlib import import_module

__all__ = [
    "BianchiAlgebra",
    "BianchiBranchPolicy",
    "FamilySpec",
    "StructureConstants",
    "build_structure_tensor",
    "build_bianchi_algebra",
    "all_bianchi_algebras",
    "get_family_spec",
    "all_family_specs",
    "rescale_bianchi_algebra",
    "get_type",
    "BackgroundState",
    "GeometryDiagnostics",
    "ResidualPack",
    "BackgroundInterpolator",
    "eta_from_t_grid",
    "background_interpolator",
    "sample_background_on_eta",
    "TetradGeometry",
    "pstf_rank2",
    "connection_from_commutators",
    "spatial_connection",
    "spatial_ricci_from_connection",
    "spatial_ricci_from_compact_formula",
    "dual_route_curvature_residual",
    "spatial_ricci",
    "div_vector",
    "div_pstf2",
    "curl_pstf2",
    "build_geometry",
    "geometry_gate_bundle",
    "MatterNormalFrameState",
    "BackgroundConstraintResiduals",
    "background_constraint_residuals",
    "evaluate_background_constraints",
    "SpeciesRestFrameState",
    "SpeciesProjectedState",
    "project_species_to_normal_frame",
    "total_matter_projection",
    "matter_projection_gate_bundle",
    "CodazziProjectionError",
    "CodazziProjectionMetadata",
    "InitialConditionMetadata",
    "OrthogonalInitialConditions",
    "TiltedInitialConditions",
    "solve_expanding_H",
    "project_shear_to_codazzi",
    "project_tilted_codazzi",
    "project_trace_free_shear",
    "build_orthogonal_initial_conditions",
    "build_tilted_initial_conditions",
    "BackgroundRhsAssembly",
    "raychaudhuri_rhs",
    "shear_rhs",
    "background_rhs",
    "assemble_background_rhs",
    "background_gate_bundle",
    "BackgroundEvolutionConfig",
    "BackgroundEvolutionResult",
    "BackgroundResidualSummary",
    "summarize_background_residuals",
    "solve_background_evolution",
    "CovariantResidualPack",
    "FamilyBranchValidationReport",
    "build_covariant_residual_pack",
    "build_family_branch_validation_report",
    "build_all_family_branch_validation_matrix",
    "WeylDiagnostics",
    "magnetic_weyl_from_curl_sigma",
    "electric_weyl_from_shear_rhs",
    "build_weyl_diagnostics",
    # V5 Round-16 PR-S1 (Codazzi-tilt evolution authority surface).
    "CodazziTiltConfig",
    "CodazziTiltEvolutionResult",
    "BackgroundEvolved",
    "evolve_codazzi_tilt_background",
    "DEFAULT_CODAZZI_RESIDUAL_THRESHOLD",
    "TILT_EVOLUTION_STATUS_EVOLVED",
    "TILT_EVOLUTION_STATUS_FROZEN",
]


_EXPORTS = {
    "BianchiAlgebra": ("bass.background.bianchi_types", "BianchiAlgebra"),
    "BianchiBranchPolicy": ("bass.background.bianchi_types", "BianchiBranchPolicy"),
    "FamilySpec": ("bass.background.bianchi_types", "FamilySpec"),
    "StructureConstants": ("bass.background.bianchi_types", "StructureConstants"),
    "build_structure_tensor": ("bass.background.bianchi_types", "build_structure_tensor"),
    "build_bianchi_algebra": ("bass.background.bianchi_types", "build_bianchi_algebra"),
    "all_bianchi_algebras": ("bass.background.bianchi_types", "all_bianchi_algebras"),
    "get_family_spec": ("bass.background.bianchi_types", "get_family_spec"),
    "all_family_specs": ("bass.background.bianchi_types", "all_family_specs"),
    "rescale_bianchi_algebra": ("bass.background.bianchi_types", "rescale_bianchi_algebra"),
    "get_type": ("bass.background.bianchi_types", "get_type"),
    "BackgroundState": ("bass.ver3_contracts", "BackgroundState"),
    "GeometryDiagnostics": ("bass.ver3_contracts", "GeometryDiagnostics"),
    "ResidualPack": ("bass.ver3_contracts", "ResidualPack"),
    "BackgroundInterpolator": ("bass.ver3_contracts", "BackgroundInterpolator"),
    "eta_from_t_grid": ("bass.ver3_contracts", "eta_from_t_grid"),
    "background_interpolator": ("bass.ver3_contracts", "background_interpolator"),
    "sample_background_on_eta": ("bass.ver3_contracts", "sample_background_on_eta"),
    "TetradGeometry": ("bass.background.geometry", "TetradGeometry"),
    "pstf_rank2": ("bass.background.geometry", "pstf_rank2"),
    "connection_from_commutators": ("bass.background.geometry", "connection_from_commutators"),
    "spatial_connection": ("bass.background.geometry", "spatial_connection"),
    "spatial_ricci_from_connection": ("bass.background.geometry", "spatial_ricci_from_connection"),
    "spatial_ricci_from_compact_formula": ("bass.background.geometry", "spatial_ricci_from_compact_formula"),
    "dual_route_curvature_residual": ("bass.background.geometry", "dual_route_curvature_residual"),
    "spatial_ricci": ("bass.background.geometry", "spatial_ricci"),
    "div_vector": ("bass.background.geometry", "div_vector"),
    "div_pstf2": ("bass.background.geometry", "div_pstf2"),
    "curl_pstf2": ("bass.background.geometry", "curl_pstf2"),
    "build_geometry": ("bass.background.geometry", "build_geometry"),
    "geometry_gate_bundle": ("bass.background.geometry", "geometry_gate_bundle"),
    "MatterNormalFrameState": ("bass.background.constraints", "MatterNormalFrameState"),
    "BackgroundConstraintResiduals": ("bass.background.constraints", "BackgroundConstraintResiduals"),
    "background_constraint_residuals": ("bass.background.constraints", "background_constraint_residuals"),
    "evaluate_background_constraints": ("bass.background.constraints", "evaluate_background_constraints"),
    "SpeciesRestFrameState": ("bass.background.matter_projection", "SpeciesRestFrameState"),
    "SpeciesProjectedState": ("bass.background.matter_projection", "SpeciesProjectedState"),
    "project_species_to_normal_frame": ("bass.background.matter_projection", "project_species_to_normal_frame"),
    "total_matter_projection": ("bass.background.matter_projection", "total_matter_projection"),
    "matter_projection_gate_bundle": ("bass.background.matter_projection", "matter_projection_gate_bundle"),
    "CodazziProjectionError": ("bass.background.initial_conditions", "CodazziProjectionError"),
    "CodazziProjectionMetadata": ("bass.background.initial_conditions", "CodazziProjectionMetadata"),
    "InitialConditionMetadata": ("bass.background.initial_conditions", "InitialConditionMetadata"),
    "OrthogonalInitialConditions": ("bass.background.initial_conditions", "OrthogonalInitialConditions"),
    "TiltedInitialConditions": ("bass.background.initial_conditions", "TiltedInitialConditions"),
    "solve_expanding_H": ("bass.background.initial_conditions", "solve_expanding_H"),
    "project_shear_to_codazzi": ("bass.background.initial_conditions", "project_shear_to_codazzi"),
    "project_tilted_codazzi": ("bass.background.initial_conditions", "project_tilted_codazzi"),
    "project_trace_free_shear": ("bass.background.initial_conditions", "project_trace_free_shear"),
    "build_orthogonal_initial_conditions": ("bass.background.initial_conditions", "build_orthogonal_initial_conditions"),
    "build_tilted_initial_conditions": ("bass.background.initial_conditions", "build_tilted_initial_conditions"),
    "BackgroundRhsAssembly": ("bass.background.rhs", "BackgroundRhsAssembly"),
    "raychaudhuri_rhs": ("bass.background.rhs", "raychaudhuri_rhs"),
    "shear_rhs": ("bass.background.rhs", "shear_rhs"),
    "background_rhs": ("bass.background.rhs", "background_rhs"),
    "assemble_background_rhs": ("bass.background.rhs", "assemble_background_rhs"),
    "background_gate_bundle": ("bass.background.rhs", "background_gate_bundle"),
    "BackgroundEvolutionConfig": ("bass.background.evolution", "BackgroundEvolutionConfig"),
    "BackgroundEvolutionResult": ("bass.background.evolution", "BackgroundEvolutionResult"),
    "BackgroundResidualSummary": ("bass.background.evolution", "BackgroundResidualSummary"),
    "summarize_background_residuals": ("bass.background.evolution", "summarize_background_residuals"),
    "solve_background_evolution": ("bass.background.evolution", "solve_background_evolution"),
    "CovariantResidualPack": ("bass.background.covariant_validation", "CovariantResidualPack"),
    "FamilyBranchValidationReport": ("bass.background.covariant_validation", "FamilyBranchValidationReport"),
    "build_covariant_residual_pack": ("bass.background.covariant_validation", "build_covariant_residual_pack"),
    "build_family_branch_validation_report": ("bass.background.covariant_validation", "build_family_branch_validation_report"),
    "build_all_family_branch_validation_matrix": ("bass.background.covariant_validation", "build_all_family_branch_validation_matrix"),
    "WeylDiagnostics": ("bass.background.weyl", "WeylDiagnostics"),
    "magnetic_weyl_from_curl_sigma": ("bass.background.weyl", "magnetic_weyl_from_curl_sigma"),
    "electric_weyl_from_shear_rhs": ("bass.background.weyl", "electric_weyl_from_shear_rhs"),
    "build_weyl_diagnostics": ("bass.background.weyl", "build_weyl_diagnostics"),
    # V5 Round-16 PR-S1 (Codazzi-tilt evolution authority surface).
    "CodazziTiltConfig": ("bass.background.codazzi_tilt_rhs", "CodazziTiltConfig"),
    "CodazziTiltEvolutionResult": (
        "bass.background.codazzi_tilt_rhs",
        "CodazziTiltEvolutionResult",
    ),
    "BackgroundEvolved": ("bass.background.codazzi_tilt_rhs", "BackgroundEvolved"),
    "evolve_codazzi_tilt_background": (
        "bass.background.codazzi_tilt_rhs",
        "evolve_codazzi_tilt_background",
    ),
    "DEFAULT_CODAZZI_RESIDUAL_THRESHOLD": (
        "bass.background.codazzi_tilt_rhs",
        "DEFAULT_CODAZZI_RESIDUAL_THRESHOLD",
    ),
    "TILT_EVOLUTION_STATUS_EVOLVED": (
        "bass.background.codazzi_tilt_rhs",
        "TILT_EVOLUTION_STATUS_EVOLVED",
    ),
    "TILT_EVOLUTION_STATUS_FROZEN": (
        "bass.background.codazzi_tilt_rhs",
        "TILT_EVOLUTION_STATUS_FROZEN",
    ),
}


def __getattr__(name: str):
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr_name = _EXPORTS[name]
    value = getattr(import_module(module_name), attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
