"""HTT-owned PR-272 vector/tensor inference-validation surface."""

from common.vector_tensor_statistical_inference import (
    CompositionIdentifiabilityReport,
    DepthMultiplicityReport,
    FiellerInterval,
    HttDepthDiscriminationReport,
    JointAnchorCoverageReport,
    JointAnchorLaw,
    MatchedCounterpairReport,
    ModelCandidate,
    OpenSetValidationReport,
    PillarSInferenceError,
    SimultaneousCalibrationReport,
    ValidationStatus,
    WeakIdentificationReport,
    build_joint_anchor_law,
    calibrate_split_max_statistic,
    evaluate_depth_local_global,
    evaluate_depth_multiplicity,
    evaluate_joint_anchor_coverage,
    evaluate_matched_counterpair_power,
    evaluate_open_set_validation,
    evaluate_registered_composition,
    evaluate_weak_identification,
    joint_fieller_interval,
    require_simultaneous_control,
)

__all__ = [
    "CompositionIdentifiabilityReport",
    "DepthMultiplicityReport",
    "FiellerInterval",
    "HttDepthDiscriminationReport",
    "JointAnchorCoverageReport",
    "JointAnchorLaw",
    "MatchedCounterpairReport",
    "ModelCandidate",
    "OpenSetValidationReport",
    "PillarSInferenceError",
    "SimultaneousCalibrationReport",
    "ValidationStatus",
    "WeakIdentificationReport",
    "build_joint_anchor_law",
    "calibrate_split_max_statistic",
    "evaluate_depth_local_global",
    "evaluate_depth_multiplicity",
    "evaluate_joint_anchor_coverage",
    "evaluate_matched_counterpair_power",
    "evaluate_open_set_validation",
    "evaluate_registered_composition",
    "evaluate_weak_identification",
    "joint_fieller_interval",
    "require_simultaneous_control",
]
