"""OBSSTAT-owned facade for repository-bound vector/tensor data preflight."""

from common.vector_tensor_data_admission import (
    AdmissionVerdict,
    ComponentBindingStatus,
    DATA_IDENTITY_EVIDENCE_SCHEMA,
    DATA_IDENTITY_REGISTRY_SCHEMA,
    DataAdmissionDecision,
    DataAdmissionError,
    DataAdmissionReport,
    DataIdentityRegistry,
    IdentityStatus,
    NO_ADMITTED_DATA_PILOT,
    PilotAuthorizationStatus,
    RepositoryComponentBinding,
    RegisteredDataIdentity,
    VectorTensorDataCandidate,
    build_data_admission_report,
    candidate_from_mapping,
    candidates_from_registry,
    evaluate_data_candidate,
    identity_registry_from_mapping,
)

__all__ = [
    "AdmissionVerdict",
    "ComponentBindingStatus",
    "DATA_IDENTITY_EVIDENCE_SCHEMA",
    "DATA_IDENTITY_REGISTRY_SCHEMA",
    "DataAdmissionDecision",
    "DataAdmissionError",
    "DataAdmissionReport",
    "DataIdentityRegistry",
    "IdentityStatus",
    "NO_ADMITTED_DATA_PILOT",
    "PilotAuthorizationStatus",
    "RepositoryComponentBinding",
    "RegisteredDataIdentity",
    "VectorTensorDataCandidate",
    "build_data_admission_report",
    "candidate_from_mapping",
    "candidates_from_registry",
    "evaluate_data_candidate",
    "identity_registry_from_mapping",
]
