ClearAll["Global`*"];
ev={ex,ey,ez};
avg[expr_]:=Total[Function[t,With[{powers=t[[1]],coeff=t[[2]]},If[AnyTrue[powers,OddQ],0,coeff Times@@(Factorial2[#-1]& /@ powers)/Factorial2[Total[powers]+1]]]] /@ CoefficientRules[Expand[expr],ev]];
sm={{s1,s3,s4},{s3,s2,s5},{s4,s5,-s1-s2}};
km=hh IdentityMatrix[3]+sm;
stf[m_]:=(m+Transpose[m])/2-Tr[m] IdentityMatrix[3]/3;
bdot=-4rho(hh+ev.sm.ev);
rhoDot=avg[bdot];
mDot=Map[avg[bdot #]&,ev];
piDot=Map[avg[bdot #]&,Outer[Times,ev,ev],{2}]-rhoDot IdentityMatrix[3]/3;
dotResidual=FullSimplify[piDot+8rho sm/15];
gLinear=IdentityMatrix[3]+2tt km;
brightnessRatio=(ev.gLinear.ev)^(-2);
ratioDot=D[brightnessRatio,tt]/.tt->0;
sphereDerivativeResidual=FullSimplify[(ratioDot+4(hh+ev.sm.ev))/.ez^2->1-ex^2-ey^2];
hamiltonian=FullSimplify[Tr[km]^2-Tr[km.km]-(6hh^2-Tr[sm.sm])];
hFamily=Sqrt[lam^2+kap rho/3];
sFamily=lam DiagonalMatrix[{2,-1,-1}];
kFamily=hFamily IdentityMatrix[3]+sFamily;
familyConstraint=FullSimplify[Tr[kFamily]^2-Tr[kFamily.kFamily]-2kap rho];
familyExpansionPositive=FullSimplify[And@@Thread[Diagonal[kFamily]>0],Assumptions->{lam>=0,kap>0,rho>0}];
normalizedNormLimit=Limit[Sqrt[Tr[sFamily.sFamily]]/hFamily,lam->Infinity,Assumptions->{kap>0,rho>0}];
hv={h1,h2,h3}; pv={pr1,pr2,pr3};
constraint=Total[hv]^2-hv.hv-2kap rho;
hDot=-Total[hv]hv+kap pv;
rhoEvolution=-Total[hv]rho-hv.pv;
constraintDot=Sum[D[constraint,hv[[i]]]hDot[[i]],{i,3}]+D[constraint,rho]rhoEvolution;
constraintPropagationResidual=FullSimplify[(constraintDot+2Total[hv]constraint)/.pr3->rho-pr1-pr2];
out=<|"scope"->"exact local algebra, no evolution", "rho_dot"->rhoDot,"m_dot"->mDot,"pi_dot"->piDot,"pi_dot_residual"->dotResidual,"brightness_derivative_on_unit_sphere_residual"->sphereDerivativeResidual,"hamiltonian_decomposition_residual"->hamiltonian,"family_constraint_residual"->familyConstraint,"all_directional_expansions_positive"->familyExpansionPositive,"normalized_shear_limit"->normalizedNormLimit,"constraint_propagation_residual"->constraintPropagationResidual,"family_norm_squared"->Tr[sFamily.sFamily],"isotropic_limit"->FullSimplify[kFamily/.lam->0]|>;
ExportString[Map[ToString[#,InputForm]&,out],"RawJSON"]
