import Mathlib
#check Matrix.toEuclideanLin
#check Matrix.toEuclideanLin_apply
#check Matrix.toEuclideanLin_one
#check Matrix.toEuclideanLin_sub
#check Matrix.toEuclideanLin_smul
#check LinearMap.singularValues_fin
#check LinearMap.IsSymmetric.hasEigenvector_eigenvectorBasis
#check LinearMap.IsSymmetric.det_eq_prod_eigenvalues
#check LinearMap.IsPositive.nonneg_eigenvalues
#check LinearMap.adjoint_apply
#check LinearMap.adjoint_comp_self
#check Matrix.det_fin_two
#check Matrix.det_eq_det_toEuclideanLin
#check LinearMap.det_toMatrix
#check norm_le_iff
#check LinearMap.toContinuousLinearMap
#check Matrix.toEuclideanLin_conjTranspose_eq_adjoint
#check EuclideanSpace.norm_eq
