"""COMMON-owned statistics harnesses for pre-solver HTT work."""

from __future__ import annotations

from .anchored_response_geometry import (
    AnchoredResponseGeometryError,
    AnchoredResponseGeometryReport,
    AnchoredResponseStatus,
    IdentifiedSetContractionReport,
    IdentifiedSetContractionStatus,
    NonlinearityDGPKind,
    NonlinearityPhaseCell,
    NonlinearityPhaseDiagramReport,
    NonlinearityPhaseStatus,
    PrincipalAngleReport,
    PrincipalAngleStatus,
    SchurMorphologyInformationReport,
    SchurMorphologyStatus,
    anchored_numeric_content_id,
    build_nonlinearity_phase_cell,
    build_nonlinearity_phase_diagram,
    measure_anchored_response_geometry,
    measure_schur_morphology_information,
)
from .mes_cov_bound import MesCovarianceBoundResult, build_mes_covariance_bound
from .mes_information_gain import (
    MesInformationGainBranch,
    MesInformationGainReport,
    build_mes_information_gain_report,
)
from .mes_information_gain_compatibility import (
    build_mes_information_gain_compatibility_view,
)
from .mes_template_bound import MesTemplateBoundResult, build_mes_template_bound
from .morphology_benchmark import (
    LowEllMorphologyBenchmarkReport,
    MorphologyBenchmarkError,
    MorphologyBenchmarkProtocol,
    MorphologyBenchmarkStatus,
    MorphologyRepresentation,
    PR257_MINIMUM_MC_REPLICATES,
    PR257_MULTIPLICITY_RULE,
    PR257_REPRESENTATIONS,
    PR257_SCORING_RULE,
    RepresentationAvailability,
    RepresentationBenchmarkInput,
    RepresentationBenchmarkResult,
    RepresentationBenchmarkStatus,
    evaluate_morphology_benchmark,
)

__all__ = [
    "AnchoredResponseGeometryError",
    "AnchoredResponseGeometryReport",
    "AnchoredResponseStatus",
    "IdentifiedSetContractionReport",
    "IdentifiedSetContractionStatus",
    "MesCovarianceBoundResult",
    "MesInformationGainBranch",
    "MesInformationGainReport",
    "MesTemplateBoundResult",
    "LowEllMorphologyBenchmarkReport",
    "MorphologyBenchmarkError",
    "MorphologyBenchmarkProtocol",
    "MorphologyBenchmarkStatus",
    "MorphologyRepresentation",
    "NonlinearityDGPKind",
    "NonlinearityPhaseCell",
    "NonlinearityPhaseDiagramReport",
    "NonlinearityPhaseStatus",
    "PrincipalAngleReport",
    "PrincipalAngleStatus",
    "PR257_MULTIPLICITY_RULE",
    "PR257_MINIMUM_MC_REPLICATES",
    "PR257_REPRESENTATIONS",
    "PR257_SCORING_RULE",
    "RepresentationAvailability",
    "RepresentationBenchmarkInput",
    "RepresentationBenchmarkResult",
    "RepresentationBenchmarkStatus",
    "SchurMorphologyInformationReport",
    "SchurMorphologyStatus",
    "anchored_numeric_content_id",
    "build_nonlinearity_phase_cell",
    "build_nonlinearity_phase_diagram",
    "build_mes_covariance_bound",
    "build_mes_information_gain_compatibility_view",
    "build_mes_information_gain_report",
    "build_mes_template_bound",
    "evaluate_morphology_benchmark",
    "measure_anchored_response_geometry",
    "measure_schur_morphology_information",
]
