#!/usr/bin/env python3
r"""Remove stale manuscript plot references and install current figure snippets.

This is intentionally conservative: it removes only LaTeX ``figure`` blocks
that contain ``\includegraphics`` from the top-level manuscript chapter files.
It does not delete legacy image files from disk. The replacement snippets are
generated by ``scripts/make_current_manuscript_figures.py``.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import shlex
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


REPO_ROOT = Path(__file__).resolve().parents[1]
MANUSCRIPT_ROOT = REPO_ROOT / "docs" / "manuscript"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "generated" / "current_manuscript_figure_curation.json"

CHAPTER_FILES = (
    "ch01_introduction.tex",
    "ch02_dipole_anomaly.tex",
    "ch03_framework.tex",
    "ch04_bianchi_bounds.tex",
    "ch05_teff_corrections.tex",
    "ch06_pipeline.tex",
    "ch07_results.tex",
    "ch08_robustness.tex",
    "ch09_discussion.tex",
    "ch10_future.tex",
    "ch11_error_hierarchy.tex",
    "appendices.tex",
)

CURRENT_SNIPPET_INPUTS = {
    "ch03_framework.tex": "generated/current_figures_framework",
    "ch06_pipeline.tex": "generated/current_figures_pipeline",
    "ch07_results.tex": "generated/current_figures_results",
    "ch11_error_hierarchy.tex": "generated/current_figures_governance",
}

CURRENT_FIGURE_LABELS = frozenset(
    {
        "fig:current-dag-progress",
        "fig:current-scalar-morphology-boundary",
        "fig:current-transfer-provenance",
        "fig:current-local-global-gates",
        "fig:current-mio-certificate-status",
        "fig:current-public-claim-freeze",
    }
)

MARKER_BEGIN = "% BEGIN current-code generated figure deck"
MARKER_END = "% END current-code generated figure deck"
FIGURE_REF_RE = re.compile(r"\\ref\{(fig:[^}]+)\}")


@dataclass(frozen=True)
class CurationResult:
    path: str
    removed_blocks: int
    removed_includes: tuple[str, ...]
    replaced_figure_refs: tuple[str, ...]
    inserted_snippet: str | None


def _repo_relative(path: Path, repo_root: Path) -> str:
    try:
        return path.relative_to(repo_root).as_posix()
    except ValueError:
        return path.as_posix()


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _git_state(repo_root: Path) -> str:
    try:
        commit = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=repo_root,
            text=True,
        ).strip()
        status = subprocess.check_output(
            ["git", "status", "--short"],
            cwd=repo_root,
            text=True,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return "git_state_unavailable"
    return f"{commit}+dirty" if status else commit


def _strip_existing_marker(text: str) -> str:
    while MARKER_BEGIN in text and MARKER_END in text:
        before, rest = text.split(MARKER_BEGIN, 1)
        _, after = rest.split(MARKER_END, 1)
        text = before.rstrip() + "\n\n" + after.lstrip()
    return text


def _extract_includegraphics(block: Iterable[str]) -> tuple[str, ...]:
    includes: list[str] = []
    for line in block:
        if "\\includegraphics" not in line:
            continue
        tail = line.split("\\includegraphics", 1)[1]
        if "{" not in tail or "}" not in tail:
            includes.append(line.strip())
            continue
        includes.append(tail.rsplit("{", 1)[-1].split("}", 1)[0].strip())
    return tuple(includes)


def _remove_graphic_figures(text: str) -> tuple[str, int, tuple[str, ...]]:
    lines = text.splitlines(keepends=True)
    output: list[str] = []
    removed_blocks = 0
    removed_includes: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if "\\begin{figure" not in line:
            output.append(line)
            i += 1
            continue

        block: list[str] = []
        depth = 0
        j = i
        while j < len(lines):
            block_line = lines[j]
            block.append(block_line)
            if "\\begin{figure" in block_line:
                depth += 1
            if "\\end{figure" in block_line:
                depth -= 1
                if depth == 0:
                    j += 1
                    break
            j += 1

        includes = _extract_includegraphics(block)
        if includes:
            removed_blocks += 1
            removed_includes.extend(includes)
            output.append(
                "% Legacy/unmanifested figure block removed by current figure curation.\n"
            )
            i = j
            continue

        output.extend(block)
        i = j

    return "".join(output), removed_blocks, tuple(removed_includes)


def _replace_stale_figure_refs(text: str) -> tuple[str, tuple[str, ...]]:
    replaced: list[str] = []

    def replace(match: re.Match[str]) -> str:
        label = match.group(1)
        if label in CURRENT_FIGURE_LABELS:
            return match.group(0)
        replaced.append(label)
        return r"\emph{legacy figure removed}"

    return FIGURE_REF_RE.sub(replace, text), tuple(replaced)


def _with_current_snippet(text: str, snippet: str | None) -> str:
    text = _strip_existing_marker(text).rstrip() + "\n"
    if snippet is None:
        return text
    return (
        text
        + "\n"
        + MARKER_BEGIN
        + "\n"
        + f"\\input{{{snippet}}}\n"
        + MARKER_END
        + "\n"
    )


def curate_file(path: Path, *, repo_root: Path) -> tuple[str, CurationResult]:
    original = path.read_text(encoding="utf-8")
    stripped_marker = _strip_existing_marker(original)
    stripped_figures, removed_blocks, removed_includes = _remove_graphic_figures(
        stripped_marker
    )
    stripped_refs, replaced_refs = _replace_stale_figure_refs(stripped_figures)
    snippet = CURRENT_SNIPPET_INPUTS.get(path.name)
    updated = _with_current_snippet(stripped_refs, snippet)
    return updated, CurationResult(
        path=_repo_relative(path, repo_root),
        removed_blocks=removed_blocks,
        removed_includes=removed_includes,
        replaced_figure_refs=replaced_refs,
        inserted_snippet=snippet,
    )


def _write_json_report(
    *,
    repo_root: Path,
    output: Path,
    results: tuple[CurationResult, ...],
    input_hashes: list[str],
    generating_command: str,
) -> None:
    total_blocks = sum(result.removed_blocks for result in results)
    total_includes = sum(len(result.removed_includes) for result in results)
    total_replaced_refs = sum(len(result.replaced_figure_refs) for result in results)
    payload = {
        "artifact_id": "common.current_manuscript_figure_curation",
        "artifact_path": _repo_relative(output, repo_root),
        "owner": "COMMON",
        "implementation_scope": "common",
        "claim_tier": "diagnostic_only",
        "production_status": "diagnostic_only",
        "transfer_source": "none",
        "sky_support_status": "not_directional",
        "null_mock_status": "not_statistical",
        "config_hash": "sha256:" + hashlib.sha256(
            json.dumps(
                {
                    "chapter_files": CHAPTER_FILES,
                    "snippet_inputs": CURRENT_SNIPPET_INPUTS,
                    "total_removed_blocks": total_blocks,
                    "total_removed_includes": total_includes,
                    "total_replaced_figure_refs": total_replaced_refs,
                },
                sort_keys=True,
            ).encode("utf-8")
        ).hexdigest(),
        "input_hashes": input_hashes,
        "caveats": [
            "Only LaTeX includegraphics references were curated; legacy image files were not deleted.",
            "Removed figure references are excluded from manuscript use until regenerated with valid manifests.",
            "Replacement snippets depend on scripts/make_current_manuscript_figures.py outputs.",
        ],
        "generating_command": generating_command,
        "git_commit_or_worktree_state": _git_state(repo_root),
        "total_removed_blocks": total_blocks,
        "total_removed_includes": total_includes,
        "total_replaced_figure_refs": total_replaced_refs,
        "inserted_snippets": {
            result.path: result.inserted_snippet
            for result in results
            if result.inserted_snippet is not None
        },
        "files": [
            {
                "path": result.path,
                "removed_blocks": result.removed_blocks,
                "removed_includes": list(result.removed_includes),
                "replaced_figure_refs": list(result.replaced_figure_refs),
                "inserted_snippet": result.inserted_snippet,
            }
            for result in results
        ],
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _command(argv: list[str] | None) -> str:
    args = sys.argv[1:] if argv is None else argv
    return shlex.join(["python", "scripts/curate_current_manuscript_figures.py", *args])


def run(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Curate manuscript figure references to current manifest-backed snippets."
    )
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    parser.add_argument("--manuscript-root", type=Path, default=MANUSCRIPT_ROOT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--write", action="store_true", help="write manuscript edits and report")
    args = parser.parse_args(argv)

    repo_root = args.repo_root.resolve()
    manuscript_root = args.manuscript_root
    if not manuscript_root.is_absolute():
        manuscript_root = repo_root / manuscript_root
    output = args.output if args.output.is_absolute() else repo_root / args.output

    paths = [manuscript_root / name for name in CHAPTER_FILES]
    input_hashes = [
        f"{_repo_relative(path, repo_root)}:sha256:{_sha256(path)}"
        for path in paths
        if path.exists()
    ]

    updates: list[tuple[Path, str]] = []
    results: list[CurationResult] = []
    for path in paths:
        if not path.exists():
            continue
        updated, result = curate_file(path, repo_root=repo_root)
        updates.append((path, updated))
        results.append(result)

    total_blocks = sum(result.removed_blocks for result in results)
    total_includes = sum(len(result.removed_includes) for result in results)
    total_replaced_refs = sum(len(result.replaced_figure_refs) for result in results)
    changed_files = sum(
        1 for path, updated in updates if path.read_text(encoding="utf-8") != updated
    )
    print(
        "current manuscript figure curation: "
        f"removed_blocks={total_blocks} removed_includes={total_includes} "
        f"replaced_figure_refs={total_replaced_refs} "
        f"changed_files={changed_files}"
    )

    if not args.write:
        return 0

    for path, updated in updates:
        if path.read_text(encoding="utf-8") != updated:
            path.write_text(updated, encoding="utf-8")

    _write_json_report(
        repo_root=repo_root,
        output=output,
        results=tuple(results),
        input_hashes=input_hashes,
        generating_command=_command(argv),
    )
    print(f"wrote {_repo_relative(output, repo_root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
