#!/usr/bin/env python3
"""Successor to the D24 figure (v9, REV-R174; answers R1 3.8 / R2's carried
M9 from the 2026-07-10 reviews).

The frozen D24 figure (``fig_data_observed_sector_response_vector``,
generated by the v7/v8-frozen ``make_report_data_analysis_figures.py``)
juxtaposed three heterogeneous proxy quantities under comparator-component
panel titles ("Sigma2 data coordinate" over a -log10 tail probability,
"Omega_tilt data coordinate" over a km/s bulk-flow amplitude, "W2
reconstruction coordinate" over a curl/shear ratio) and called the triple an
"observed-sector response vector" — a category error against the report's
own dimensionless g-vector definition.

This successor renders the SAME underlying data (pr08_006_joint_artifact)
with honest names:

    K1 low-ell global-tail diagnostic     (-log10 tail, SMICA/Commander)
    CF4 bulk-flow amplitude B_CF4         (km/s, native units, NEVER folded
                                           into a g-vector)
    K6 reconstruction curl/shear ratio    (dimensionless reconstruction
                                           diagnostic, not the comparator W^2)

as ``fig_data_observed_sector_proxy_coordinates``. The frozen figure and its
generator are untouched (they ship in the byte-frozen v7/v8 packages); the
v9 report references THIS artifact instead. ``--check`` diffs the sidecars.

Claim discipline: diagnostic-only presentation of prepared data coordinates;
no posterior odds, no p-value without a null ensemble, no geometry claim.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]
FIGURE_DIR = REPO_ROOT / "figures" / "data_analysis_current"
JOINT = REPO_ROOT / "docs/generated/pr08_006_joint_artifact.json"
STEM = "fig_data_observed_sector_proxy_coordinates"
SCRIPT_PATH = "scripts/make_data_proxy_coordinates_figure.py"

COLORS = {"blue": "#3465a4", "cyan": "#06989a", "green": "#4e9a06",
          "red": "#cc0000", "slate": "#555753"}


def _sha(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _render(sectors: dict) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(11.2, 4.1))
    sigma = sectors["Sigma2"]
    axes[0].bar(
        ["SMICA", "Commander"],
        [-np.log10(float(sigma["global_p_smica"])),
         -np.log10(float(sigma["global_p_commander"]))],
        color=[COLORS["blue"], COLORS["cyan"]], alpha=0.75)
    axes[0].set_ylabel("-log10 global tail")
    axes[0].set_title("K1 low-ell global-tail diagnostic")
    omega = sectors["Omega_tilt"]
    axes[1].bar(["CF4 |B|"], [float(omega["value_kms"])],
                color=COLORS["green"], alpha=0.75)
    axes[1].errorbar([0], [float(omega["value_kms"])],
                     yerr=[float(omega["error_kms"])],
                     color=COLORS["slate"], capsize=3.0, fmt="none")
    axes[1].set_ylabel("km/s")
    axes[1].set_title("CF4 bulk-flow amplitude $B_{\\rm CF4}$")
    w2 = sectors["W2"]
    axes[2].bar(["max W/shear"], [float(w2["vorticity_over_shear_max"])],
                color=COLORS["red"], alpha=0.75)
    axes[2].set_ylabel("ratio")
    axes[2].set_title("K6 reconstruction curl/shear ratio")
    fig.suptitle("Available observed-sector proxy coordinates "
                 "(heterogeneous units; NOT comparator components)",
                 fontsize=12)
    fig.tight_layout()
    fig.savefig(FIGURE_DIR / f"{STEM}.png", dpi=180, bbox_inches="tight",
                facecolor="white")
    plt.close(fig)


def _payloads() -> tuple[dict, dict]:
    joint = json.loads(JOINT.read_text())
    sectors = joint["sectors"]
    source = {
        "figure_id": STEM,
        "successor_of": "fig_data_observed_sector_response_vector "
                        "(frozen v7/v8 packages; comparator-component panel "
                        "titles retired)",
        "panels": {
            "k1_low_ell_global_tail": {
                "minus_log10_global_p_smica":
                    -float(np.log10(float(sectors["Sigma2"]["global_p_smica"]))),
                "minus_log10_global_p_commander":
                    -float(np.log10(float(sectors["Sigma2"]["global_p_commander"]))),
                "not_the_comparator_Sigma2": True,
            },
            "cf4_bulk_flow_amplitude": {
                "value_kms": float(sectors["Omega_tilt"]["value_kms"]),
                "error_kms": float(sectors["Omega_tilt"]["error_kms"]),
                "units": "km/s",
                "never_folded_into_a_g_vector": True,
            },
            "k6_reconstruction_curl_shear_ratio": {
                "vorticity_over_shear_max":
                    float(sectors["W2"]["vorticity_over_shear_max"]),
                "not_the_comparator_W2": True,
            },
        },
        "unit_heterogeneity": ["dimensionless tail transform", "km/s",
                               "dimensionless reconstruction ratio"],
    }
    manifest = {
        "allowed_use": "paper_appendix",
        "artifact_id": "obsstat.report_data.observed_sector_proxy_coordinates",
        "artifact_mode": "paper_appendix_conditioned",
        "artifact_path": f"figures/data_analysis_current/{STEM}.png",
        "caption_policy": [
            "must_state_observed_data_diagnostic",
            "must_state_proxy_not_comparator_component",
            "must_not_state_family_identification",
            "must_not_state_native_low_ell_solver_output",
            "must_not_state_p_value_without_null_ensemble",
        ],
        "caveats": [
            "Observed/prepared data analysis figure.",
            "The three panels are heterogeneous PROXY coordinates (tail "
            "transform, km/s amplitude, reconstruction ratio); none is a "
            "comparator component and the triple is NOT a g-vector.",
            "Diagnostic-only: no posterior odds, p-value, geometry "
            "detection, or family identification.",
            "No native low-ell solver output is used.",
        ],
        "claim_tier": "diagnostic_only",
        "code_version": "content-addressed",
        "created_by": SCRIPT_PATH,
        "generating_command": f"python {SCRIPT_PATH}",
        "git_commit": "content-addressed",
        "git_commit_or_worktree_state": "content-addressed",
        "implementation_scope": "obsstat",
        "input_hashes": [
            f"docs/generated/pr08_006_joint_artifact.json:{_sha(JOINT)}",
        ],
        "null_mock_status": "mixed_by_sector",
        "owner": "OBSSTAT",
        "production_status": "diagnostic_only",
        "schema_version": "obsstat.report_data_analysis_figure.v1",
        "sky_support_status": "not_directional",
        "source": source,
    }
    manifest["config_hash"] = "sha256:" + hashlib.sha256(
        json.dumps(source, sort_keys=True).encode()).hexdigest()
    return source, manifest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    source, manifest = _payloads()
    src_text = json.dumps(source, indent=2, sort_keys=True) + "\n"
    man_text = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    src_path = FIGURE_DIR / f"{STEM}.source.json"
    man_path = FIGURE_DIR / f"{STEM}.manifest.json"
    if args.check:
        stale = [str(p) for p, t in ((src_path, src_text), (man_path, man_text))
                 if not p.exists() or p.read_text() != t]
        if stale:
            print("stale proxy-coordinates figure sidecars:\n  "
                  + "\n  ".join(stale), file=sys.stderr)
            return 1
        print("proxy-coordinates figure sidecars current")
        return 0
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    _render(json.loads(JOINT.read_text())["sectors"])
    src_path.write_text(src_text)
    man_path.write_text(man_text)
    print(f"wrote figures/data_analysis_current/{STEM}.png (+ sidecars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
