#!/usr/bin/env python3
"""Plot low-ell FLRW spectra against the shipped CAMB reference.

The current repository has:

- CAMB Planck-2018 TT/EE/TE reference in ``data/camb_ref_planck2018.npz``.
- BASS Rust MB-95 FLRW TT oracle in ``tests_log/dl_spectrum_mb95_oracle.csv``.

It can also overlay a real Python PSTF spectrum archive generated by
``scripts/export_flrw_lowell_pstf_spectrum.py``.  Without that archive,
only the Rust MB-95 TT oracle is compared to CAMB and CAMB EE/TE remain
reference-only panels.
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def _load_camb(path: Path) -> dict[str, np.ndarray]:
    data = np.load(path, allow_pickle=True)
    required = {"ell", "C_TT", "C_EE", "C_TE", "D_TT", "D_EE", "D_TE"}
    missing = required.difference(data.files)
    if missing:
        raise ValueError(f"{path} missing CAMB fields: {sorted(missing)}")
    return {key: np.asarray(data[key]) for key in required}


def _load_bass_tt(path: Path) -> tuple[np.ndarray, np.ndarray]:
    ell: list[int] = []
    d_tt: list[float] = []
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            ell.append(int(row["ell"]))
            d_tt.append(float(row["D_ell"]))
    if not ell:
        raise ValueError(f"{path} did not contain any BASS TT rows")
    return np.asarray(ell, dtype=np.int64), np.asarray(d_tt, dtype=np.float64)


def _load_optional_bass_pipeline(path: Path | None) -> dict[str, np.ndarray] | None:
    if path is None:
        return None
    data = np.load(path, allow_pickle=True)
    keys = set(data.files)
    if "ell" in keys:
        ell = np.asarray(data["ell"], dtype=np.int64)
    elif "d_tt" in keys:
        ell = np.arange(np.asarray(data["d_tt"]).size, dtype=np.int64)
    elif "D_TT" in keys:
        ell = np.arange(np.asarray(data["D_TT"]).size, dtype=np.int64)
    else:
        raise ValueError(
            f"{path} needs an 'ell' field or one of 'd_tt'/'D_TT'"
        )

    def optional_array(*names: str) -> np.ndarray | None:
        for name in names:
            if name in keys:
                arr = np.asarray(data[name], dtype=np.float64)
                if arr.shape != ell.shape:
                    raise ValueError(
                        f"{path}:{name} shape {arr.shape} does not match ell {ell.shape}"
                    )
                return arr
        return None

    out: dict[str, np.ndarray] = {"ell": ell}
    for target, names in {
        "D_TT": ("D_TT", "d_tt"),
        "D_EE": ("D_EE", "d_ee"),
        "D_TE": ("D_TE", "d_te"),
        "C_TT": ("C_TT", "cl_tt"),
        "C_EE": ("C_EE", "cl_ee"),
        "C_TE": ("C_TE", "cl_te"),
    }.items():
        arr = optional_array(*names)
        if arr is not None:
            out[target] = arr
    return out


def _to_c_ell(ell: np.ndarray, d_ell: np.ndarray) -> np.ndarray:
    return (2.0 * np.pi * d_ell) / (ell * (ell + 1.0))


def _intersect_by_ell(
    ref_ell: np.ndarray,
    ref_values: np.ndarray,
    candidate_ell: np.ndarray,
    candidate_values: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    ref = {int(ell): float(value) for ell, value in zip(ref_ell, ref_values)}
    cand = {
        int(ell): float(value)
        for ell, value in zip(candidate_ell, candidate_values)
    }
    common = np.asarray(sorted(set(ref).intersection(cand)), dtype=np.int64)
    return (
        common,
        np.asarray([ref[int(ell)] for ell in common], dtype=np.float64),
        np.asarray([cand[int(ell)] for ell in common], dtype=np.float64),
    )


def _style_axes(ax) -> None:
    ax.grid(True, which="major", alpha=0.25, linewidth=0.8)
    ax.tick_params(axis="both", labelsize=9)


def plot_comparison(
    *,
    camb_path: Path,
    bass_tt_path: Path,
    bass_pipeline_path: Path | None,
    out_dir: Path,
    ell_max: int,
) -> list[Path]:
    camb = _load_camb(camb_path)
    bass_ell, bass_d_tt = _load_bass_tt(bass_tt_path)
    bass_pipeline = _load_optional_bass_pipeline(bass_pipeline_path)

    camb_mask = camb["ell"] <= ell_max
    camb_ell = camb["ell"][camb_mask]
    bass_mask = bass_ell <= ell_max
    bass_ell = bass_ell[bass_mask]
    bass_d_tt = bass_d_tt[bass_mask]
    bass_c_tt = _to_c_ell(bass_ell.astype(np.float64), bass_d_tt)

    common_ell, camb_d_common, bass_d_common = _intersect_by_ell(
        camb_ell,
        camb["D_TT"][camb_mask],
        bass_ell,
        bass_d_tt,
    )
    rel_tt = (bass_d_common - camb_d_common) / camb_d_common

    out_dir.mkdir(parents=True, exist_ok=True)

    paths: list[Path] = []
    fig, axes = plt.subplots(2, 2, figsize=(11.5, 8.0), constrained_layout=True)
    ax = axes[0, 0]
    ax.plot(camb_ell, camb["D_TT"][camb_mask], "o-", label="CAMB TT", color="#1f77b4")
    ax.plot(bass_ell, bass_d_tt, "s--", label="BASS Rust MB-95 TT", color="#d62728")
    ax.set_title("FLRW low-ell TT: D_l")
    ax.set_xlabel("ell")
    ax.set_ylabel("D_l^TT [uK^2]")
    ax.legend(fontsize=8)
    _style_axes(ax)

    ax = axes[0, 1]
    ax.axhline(0.0, color="black", linewidth=0.9)
    ax.plot(common_ell, 100.0 * rel_tt, "o-", color="#9467bd")
    ax.set_title("BASS TT residual vs CAMB")
    ax.set_xlabel("ell")
    ax.set_ylabel("(BASS - CAMB) / CAMB [%]")
    _style_axes(ax)

    ax = axes[1, 0]
    ax.plot(camb_ell, camb["D_EE"][camb_mask], "o-", color="#2ca02c")
    if bass_pipeline is not None and "D_EE" in bass_pipeline:
        mask = bass_pipeline["ell"] <= ell_max
        ax.plot(
            bass_pipeline["ell"][mask],
            bass_pipeline["D_EE"][mask],
            "s--",
            color="#d62728",
            label="BASS Python PSTF EE",
        )
        ax.legend(fontsize=8)
    ax.set_title(
        "FLRW low-ell EE: D_l"
        if bass_pipeline is not None and "D_EE" in bass_pipeline
        else "CAMB low-ell EE reference"
    )
    ax.set_xlabel("ell")
    ax.set_ylabel("D_l^EE [uK^2]")
    if bass_pipeline is None or "D_EE" not in bass_pipeline:
        ax.text(
            0.03,
            0.92,
            "BASS EE FLRW comparison is not publication-ready in this repo state.",
            transform=ax.transAxes,
            fontsize=8,
            va="top",
        )
    _style_axes(ax)

    ax = axes[1, 1]
    ax.plot(camb_ell, camb["D_TE"][camb_mask], "o-", color="#ff7f0e")
    if bass_pipeline is not None and "D_TE" in bass_pipeline:
        mask = bass_pipeline["ell"] <= ell_max
        ax.plot(
            bass_pipeline["ell"][mask],
            bass_pipeline["D_TE"][mask],
            "s--",
            color="#d62728",
            label="BASS Python PSTF TE",
        )
        ax.legend(fontsize=8)
    ax.axhline(0.0, color="black", linewidth=0.9)
    ax.set_title(
        "FLRW low-ell TE: D_l"
        if bass_pipeline is not None and "D_TE" in bass_pipeline
        else "CAMB low-ell TE reference"
    )
    ax.set_xlabel("ell")
    ax.set_ylabel("D_l^TE [uK^2]")
    if bass_pipeline is None or "D_TE" not in bass_pipeline:
        ax.text(
            0.03,
            0.92,
            "BASS TE FLRW comparison is not publication-ready in this repo state.",
            transform=ax.transAxes,
            fontsize=8,
            va="top",
        )
    _style_axes(ax)

    path = out_dir / f"flrw_lowell_dell_camb_bass_lmax{ell_max}.png"
    fig.savefig(path, dpi=180)
    plt.close(fig)
    paths.append(path)

    fig, axes = plt.subplots(1, 3, figsize=(13.0, 3.7), constrained_layout=True)
    ax = axes[0]
    ax.plot(camb_ell, camb["C_TT"][camb_mask], "o-", label="CAMB TT", color="#1f77b4")
    ax.plot(bass_ell, bass_c_tt, "s--", label="BASS Rust MB-95 TT", color="#d62728")
    ax.set_title("C_l^TT")
    ax.set_xlabel("ell")
    ax.set_ylabel("C_l [uK^2]")
    ax.legend(fontsize=8)
    _style_axes(ax)

    ax = axes[1]
    ax.plot(camb_ell, camb["C_EE"][camb_mask], "o-", color="#2ca02c")
    if bass_pipeline is not None and "C_EE" in bass_pipeline:
        mask = bass_pipeline["ell"] <= ell_max
        ax.plot(
            bass_pipeline["ell"][mask],
            bass_pipeline["C_EE"][mask],
            "s--",
            color="#d62728",
        )
    ax.set_title(
        "C_l^EE"
        if bass_pipeline is not None and "C_EE" in bass_pipeline
        else "C_l^EE CAMB reference"
    )
    ax.set_xlabel("ell")
    ax.set_ylabel("C_l [uK^2]")
    _style_axes(ax)

    ax = axes[2]
    ax.plot(camb_ell, camb["C_TE"][camb_mask], "o-", color="#ff7f0e")
    if bass_pipeline is not None and "C_TE" in bass_pipeline:
        mask = bass_pipeline["ell"] <= ell_max
        ax.plot(
            bass_pipeline["ell"][mask],
            bass_pipeline["C_TE"][mask],
            "s--",
            color="#d62728",
        )
    ax.axhline(0.0, color="black", linewidth=0.9)
    ax.set_title(
        "C_l^TE"
        if bass_pipeline is not None and "C_TE" in bass_pipeline
        else "C_l^TE CAMB reference"
    )
    ax.set_xlabel("ell")
    ax.set_ylabel("C_l [uK^2]")
    _style_axes(ax)

    path = out_dir / f"flrw_lowell_cell_camb_bass_lmax{ell_max}.png"
    fig.savefig(path, dpi=180)
    plt.close(fig)
    paths.append(path)
    return paths


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--camb-ref",
        type=Path,
        default=Path("data/camb_ref_planck2018.npz"),
    )
    parser.add_argument(
        "--bass-tt",
        type=Path,
        default=Path("tests_log/dl_spectrum_mb95_oracle.csv"),
    )
    parser.add_argument(
        "--bass-pipeline-npz",
        type=Path,
        default=None,
        help=(
            "optional Python PSTF spectrum archive with d_tt/d_ee/d_te "
            "and/or cl_tt/cl_ee/cl_te fields"
        ),
    )
    parser.add_argument("--ell-max", type=int, default=30)
    parser.add_argument("--out-dir", type=Path, default=Path("figures/validation"))
    args = parser.parse_args()
    paths = plot_comparison(
        camb_path=args.camb_ref,
        bass_tt_path=args.bass_tt,
        bass_pipeline_path=args.bass_pipeline_npz,
        out_dir=args.out_dir,
        ell_max=int(args.ell_max),
    )
    for path in paths:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
