#!/usr/bin/env python3
"""VER2 artifact/manuscript skeleton exporter.

This script is the SK-09D solver-independent export surface. It does not
promote figures or manuscript claims. Instead it renders placeholder
manuscript snippets, Markdown mirrors, and a figure-manifest audit that all
bind to the canonical shared contracts under ``htt/src/common``.

Usage:
    venv/bin/python scripts/ver2_artifact_export.py
    venv/bin/python scripts/ver2_artifact_export.py --check
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from dataclasses import fields
from pathlib import Path
from textwrap import dedent


REPO_ROOT = Path(__file__).resolve().parents[1]
COMMON_ROOT = REPO_ROOT / "htt" / "src"
if str(COMMON_ROOT) not in sys.path:
    sys.path.insert(0, str(COMMON_ROOT))

from common.contracts import ArtifactManifest, ClaimLedgerEntry, StatusSnapshotEntry


STATUS_JSON = REPO_ROOT / "docs" / "ver2_upgrade" / "generated" / "status_snapshot.json"
CLAIM_JSON = REPO_ROOT / "docs" / "ver2_upgrade" / "generated" / "claim_ledger.json"
VER2_GEN = REPO_ROOT / "docs" / "ver2_upgrade" / "generated"
MANUSCRIPT_GEN = REPO_ROOT / "docs" / "manuscript" / "generated"
FIGURE_ROOT = REPO_ROOT / "figures" / "paper"


def _field_names(contract: type[object]) -> list[str]:
    return [field.name for field in fields(contract)]


def _load_rows(path: Path, required_fields: list[str]) -> list[dict[str, object]] | None:
    if not path.exists():
        return None
    payload = json.loads(path.read_text())
    if not isinstance(payload, list):
        raise ValueError(f"{path} must contain a JSON list")
    rows: list[dict[str, object]] = []
    for index, row in enumerate(payload):
        if not isinstance(row, dict):
            raise ValueError(f"{path} row {index} is not a JSON object")
        missing = [name for name in required_fields if name not in row]
        if missing:
            raise ValueError(f"{path} row {index} missing required fields: {missing}")
        rows.append(row)
    return rows


def _escape_tex(text: object) -> str:
    value = str(text)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    for old, new in replacements.items():
        value = value.replace(old, new)
    return value


def _scan_figures(root: Path) -> list[dict[str, object]]:
    figures: dict[tuple[str, str], dict[str, object]] = {}
    for asset in sorted(root.rglob("*")):
        if not asset.is_file():
            continue
        suffixes = asset.suffixes
        if suffixes[-1:] in ([".png"], [".pdf"]):
            stem = asset.stem
        elif suffixes[-2:] == [".caption", ".txt"]:
            stem = asset.name[:-len(".caption.txt")]
        elif suffixes[-2:] == [".manifest", ".json"]:
            stem = asset.name[:-len(".manifest.json")]
        else:
            continue
        chapter = asset.parent.relative_to(root).as_posix()
        key = (chapter, stem)
        entry = figures.setdefault(
            key,
            {
                "chapter": chapter,
                "stem": stem,
                "has_png": False,
                "has_pdf": False,
                "has_caption": False,
                "has_manifest": False,
            },
        )
        if suffixes[-1:] == [".png"]:
            entry["has_png"] = True
        elif suffixes[-1:] == [".pdf"]:
            entry["has_pdf"] = True
        elif suffixes[-2:] == [".caption", ".txt"]:
            entry["has_caption"] = True
        elif suffixes[-2:] == [".manifest", ".json"]:
            entry["has_manifest"] = True
    ordered = sorted(figures.values(), key=lambda row: (row["chapter"], row["stem"]))
    for row in ordered:
        assets = []
        if row["has_png"]:
            assets.append("png")
        if row["has_pdf"]:
            assets.append("pdf")
        if row["has_caption"]:
            assets.append("caption")
        row["assets"] = ", ".join(assets) or "none"
        row["export_status"] = (
            "manifest_ready" if row["has_manifest"] else "blocked_no_manifest"
        )
    return ordered


def _render_status_markdown(
    rows: list[dict[str, object]] | None,
    status_fields: list[str],
) -> str:
    header = dedent(
        """\
        <!-- Generated by scripts/ver2_artifact_export.py -->
        # VER2 Status Snapshot

        Semantic source: `htt/src/common/contracts.py::StatusSnapshotEntry`
        """
    )
    if rows is None:
        field_line = ", ".join(f"`{name}`" for name in status_fields)
        return header + dedent(
            f"""\

            No `status_snapshot.json` is published yet.

            Until `IM-08V` emits `docs/ver2_upgrade/generated/status_snapshot.json`,
            manuscript-facing status counts remain intentionally omitted. The shared
            snapshot contract is already frozen; required fields are: {field_line}.
            """
        )

    by_owner = Counter(str(row["owner"]) for row in rows)
    total = len(rows)
    implemented = sum(bool(row["implemented"]) for row in rows)
    smoke_tested = sum(bool(row["smoke_tested"]) for row in rows)
    production_validated = sum(bool(row["production_validated"]) for row in rows)
    manuscript_used = sum(bool(row["manuscript_used"]) for row in rows)
    table = "\n".join(
        f"| `{owner}` | {count} |" for owner, count in sorted(by_owner.items())
    )
    return header + dedent(
        f"""\

        | Metric | Count |
        | --- | ---: |
        | Total rows | {total} |
        | Implemented | {implemented} |
        | Smoke tested | {smoke_tested} |
        | Production validated | {production_validated} |
        | Manuscript used | {manuscript_used} |

        | Owner | Rows |
        | --- | ---: |
        {table}
        """
    )


def _render_claim_markdown(
    rows: list[dict[str, object]] | None,
    claim_fields: list[str],
) -> str:
    header = dedent(
        """\
        <!-- Generated by scripts/ver2_artifact_export.py -->
        # VER2 Claim Ledger

        Semantic source: `htt/src/common/contracts.py::ClaimLedgerEntry`
        """
    )
    if rows is None:
        field_line = ", ".join(f"`{name}`" for name in claim_fields)
        return header + dedent(
            f"""\

            No `claim_ledger.json` is published yet.

            Until `IM-08V` emits `docs/ver2_upgrade/generated/claim_ledger.json`,
            manuscript wording must not invent claim-tier counts or promotion states.
            The shared claim-ledger contract is already frozen; required fields are:
            {field_line}.
            """
        )

    by_tier = Counter(str(row["claim_tier"]) for row in rows)
    table = "\n".join(
        f"| `{tier}` | {count} |" for tier, count in sorted(by_tier.items())
    )
    return header + dedent(
        f"""\

        | Claim tier | Rows |
        | --- | ---: |
        {table}

        The detailed allowed/forbidden-claim rows remain owned by the JSON
        artifact so manuscript text does not drift away from the shared ledger.
        """
    )


def _render_result_pack_index() -> str:
    return dedent(
        """\
        <!-- Generated by scripts/ver2_artifact_export.py -->
        # VER2 Result-Pack Index

        Skeleton result-pack registry for `PR-MAN-15`. These packs exist only as
        placeholder manuscript/export targets until `IM-09D-FIG` and `IM-10D-MAN`
        land on top of manifest-backed artifacts.

        | Pack | Target | Current status | Unblock at |
        | --- | --- | --- | --- |
        | `A` | scalar-to-morphology bridge | blocked: missing manifests and validation campaigns | `IM-08V`, `IM-09D-FIG` |
        | `B` | local-vs-global discrimination | blocked: missing manifests and HTT production gates | `IM-06H`, `IM-08V`, `IM-09D-FIG` |
        | `C` | departure cards (`x/Q/Pi/F/G`) | blocked: missing atlas/report producers | `IM-04O`, `IM-06H`, `IM-07M` |
        | `D` | MIO certificate pack | blocked: missing MIO production artifacts and TSC overlay attachments | `IM-05T`, `IM-07M`, `IM-09D-FIG` |
        | `E` | equivalence / discrimination classes | blocked: missing theorem-to-test registry and validation registry | `IM-06H`, `IM-08V` |
        """
    )


def _render_titlepage_status_tex(rows: list[dict[str, object]] | None) -> str:
    if rows is None:
        body = dedent(
            r"""
\textbf{VER2 status hook.}
Exact module, test, and promotion counts are intentionally omitted until
\texttt{docs/ver2_upgrade/generated/status_snapshot.json} exists. This
manuscript skeleton pulls status from the shared snapshot rather than
hand-maintained counts.
"""
        ).strip()
    else:
        implemented = sum(bool(row["implemented"]) for row in rows)
        smoke_tested = sum(bool(row["smoke_tested"]) for row in rows)
        production_validated = sum(bool(row["production_validated"]) for row in rows)
        manuscript_used = sum(bool(row["manuscript_used"]) for row in rows)
        body = dedent(
            f"""
\\textbf{{VER2 status hook.}}
Snapshot-backed counts: implemented={implemented}, smoke-tested={smoke_tested},
production-validated={production_validated}, manuscript-used={manuscript_used}.
"""
        ).strip()
    return "% Generated by scripts/ver2_artifact_export.py\n" + body + "\n"


def _render_status_snapshot_tex(rows: list[dict[str, object]] | None) -> str:
    if rows is None:
        return dedent(
            r"""
% Generated by scripts/ver2_artifact_export.py
\paragraph{VER2 shared status snapshot hook.}
The manuscript does not maintain package or test counts by hand. When
\texttt{docs/ver2_upgrade/generated/status_snapshot.json} is published,
this insertion point will render the snapshot-backed summary table.
Until then, new status counts remain intentionally suppressed.
"""
        ).strip() + "\n"

    by_owner = Counter(str(row["owner"]) for row in rows)
    total = len(rows)
    implemented = sum(bool(row["implemented"]) for row in rows)
    smoke_tested = sum(bool(row["smoke_tested"]) for row in rows)
    production_validated = sum(bool(row["production_validated"]) for row in rows)
    owner_rows = "\n".join(
        f"{_escape_tex(owner)} & {count} \\\\" for owner, count in sorted(by_owner.items())
    )
    return dedent(
        f"""
% Generated by scripts/ver2_artifact_export.py
\\paragraph{{VER2 shared status snapshot hook.}}
Snapshot totals: total rows {total}, implemented {implemented},
smoke-tested {smoke_tested}, production-validated {production_validated}.

\\begin{{center}}
\\begin{{tabular}}{{lr}}
\\hline
Owner & Rows \\\\
\\hline
{owner_rows}
\\hline
\\end{{tabular}}
\\end{{center}}
"""
    ).strip() + "\n"


def _render_claim_ledger_tex(rows: list[dict[str, object]] | None) -> str:
    if rows is None:
        return dedent(
            r"""
% Generated by scripts/ver2_artifact_export.py
\paragraph{VER2 claim-ledger hook.}
Claim-tier wording is deferred to the shared
\texttt{claim_ledger.json}. Until that artifact exists, this manuscript
skeleton may describe ownership boundaries and blocked states, but it may
not count or promote claims by hand.
"""
        ).strip() + "\n"

    by_tier = Counter(str(row["claim_tier"]) for row in rows)
    tier_rows = "\n".join(
        f"{_escape_tex(tier)} & {count} \\\\" for tier, count in sorted(by_tier.items())
    )
    return dedent(
        f"""
% Generated by scripts/ver2_artifact_export.py
\\paragraph{{VER2 claim-ledger hook.}}
\\begin{{center}}
\\begin{{tabular}}{{lr}}
\\hline
Claim tier & Rows \\\\
\\hline
{tier_rows}
\\hline
\\end{{tabular}}
\\end{{center}}
"""
    ).strip() + "\n"


def _render_artifact_policy_tex(
    manifest_fields: list[str],
    figures: list[dict[str, object]],
) -> str:
    missing = sum(not bool(row["has_manifest"]) for row in figures)
    total = len(figures)
    field_list = ", ".join(f"\\texttt{{{_escape_tex(name)}}}" for name in manifest_fields)
    return dedent(
        f"""\
        % Generated by scripts/ver2_artifact_export.py
        \\paragraph{{Artifact-first export hook.}}
        Figures and tables remain blocked from VER2 manuscript promotion unless a
        canonical \\texttt{{ArtifactManifest}} is present. Required manifest fields
        remain owned by \\texttt{{common.contracts}} and are not redefined here:
        {field_list}.

        \\paragraph{{Current figure-manifest audit.}}
        The paper figure tree currently exposes {total} figure bases, of which
        {missing} are still blocked by missing manifests. The audit lives in
        \\texttt{{figures/paper/VER2\\_MANIFEST\\_INDEX.md}} and exists so
        \\textit{{no figure without manifest}} can be enforced before
        \\texttt{{IM-09D-FIG}}.
        """
    )


def _render_tsc_scope_boundary_tex() -> str:
    return dedent(
        r"""
% Generated by scripts/ver2_artifact_export.py
\paragraph{TSC scope boundary.}
The active-service TSC layer is an advisory and quarantine surface. It may
diagnose domain failure, residual inadequacy, or source/propagation mismatch,
but it does not own the forward solver, the final runtime allow/block
decision, or posterior/evidence semantics.
"""
    ).strip() + "\n"


def _render_source_vs_propagation_tex() -> str:
    return dedent(
        r"""
% Generated by scripts/ver2_artifact_export.py
\paragraph{Source versus propagation split.}
VER2 keeps source generation, anisotropic propagation, and observable
interpretation as separate ownership layers. TSC commentary may attach to any
of those layers, but it cannot collapse them into a single truth label for
the manuscript.
"""
    ).strip() + "\n"


def _render_channel_responsibility_tex() -> str:
    return dedent(
        r"""
% Generated by scripts/ver2_artifact_export.py
\paragraph{Cross-package responsibility.}
BASS owns runtime and observer-neutral forward outputs. HTT owns
directional likelihoods, posterior, and evidence. MIO owns
model-independent diagnostics and certificates. TSC owns adequacy overlays,
caveats, and quarantine hooks. This insertion point exists so manuscript
wording cannot silently swap one package's responsibility onto another.
"""
    ).strip() + "\n"


def _render_manifest_index(
    figures: list[dict[str, object]],
    manifest_fields: list[str],
) -> str:
    missing = sum(not bool(row["has_manifest"]) for row in figures)
    rows = "\n".join(
        (
            f"| `{row['chapter']}` | `{row['stem']}` | {row['assets']} | "
            f"{'yes' if row['has_manifest'] else 'no'} | `{row['export_status']}` |"
        )
        for row in figures
    )
    field_line = ", ".join(f"`{name}`" for name in manifest_fields)
    return dedent(
        f"""
<!-- Generated by scripts/ver2_artifact_export.py -->
# VER2 Figure Manifest Index

This is the SK-09D manifest audit surface for the legacy paper figure tree.
It does not promote any figure. It records which figure bases already have
the minimum file trio (`png`, `pdf`, `caption`) and whether the canonical
`ArtifactManifest` sidecar exists.

Current state:
- Figure bases scanned: {len(figures)}
- Missing manifests: {missing}
- Export rule: no figure or table may be promoted into the VER2 manuscript
  path unless a matching `.manifest.json` exists.
- Canonical manifest fields remain owned by `common.contracts`:
  {field_line}

| Chapter | Figure base | Assets | Manifest | Export status |
| --- | --- | --- | --- | --- |
{rows}
"""
    ).strip() + "\n"


def _render_all(
    status_rows: list[dict[str, object]] | None,
    claim_rows: list[dict[str, object]] | None,
    figures: list[dict[str, object]],
) -> dict[Path, str]:
    status_fields = _field_names(StatusSnapshotEntry)
    claim_fields = _field_names(ClaimLedgerEntry)
    manifest_fields = _field_names(ArtifactManifest)
    return {
        VER2_GEN / "STATUS_SNAPSHOT.md": _render_status_markdown(status_rows, status_fields),
        VER2_GEN / "CLAIM_LEDGER.md": _render_claim_markdown(claim_rows, claim_fields),
        VER2_GEN / "RESULT_PACK_INDEX.md": _render_result_pack_index(),
        MANUSCRIPT_GEN / "ver2_titlepage_status.tex": _render_titlepage_status_tex(status_rows),
        MANUSCRIPT_GEN / "ver2_status_snapshot.tex": _render_status_snapshot_tex(status_rows),
        MANUSCRIPT_GEN / "ver2_claim_ledger.tex": _render_claim_ledger_tex(claim_rows),
        MANUSCRIPT_GEN / "ver2_artifact_export_policy.tex": _render_artifact_policy_tex(
            manifest_fields,
            figures,
        ),
        MANUSCRIPT_GEN / "ver2_tsc_scope_boundary.tex": _render_tsc_scope_boundary_tex(),
        MANUSCRIPT_GEN / "ver2_source_vs_propagation.tex": _render_source_vs_propagation_tex(),
        MANUSCRIPT_GEN / "ver2_channel_responsibility.tex": _render_channel_responsibility_tex(),
        FIGURE_ROOT / "VER2_MANIFEST_INDEX.md": _render_manifest_index(
            figures,
            manifest_fields,
        ),
    }


def _write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content.rstrip() + "\n")


def _check_outputs(outputs: dict[Path, str]) -> int:
    stale: list[str] = []
    for path, content in outputs.items():
        expected = content.rstrip() + "\n"
        actual = path.read_text() if path.exists() else None
        if actual != expected:
            stale.append(path.relative_to(REPO_ROOT).as_posix())
    if stale:
        print("Out-of-date VER2 export surfaces:")
        for path in stale:
            print(f"  - {path}")
        return 1
    print("VER2 export surfaces are up to date.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated export surfaces are missing or stale",
    )
    args = parser.parse_args()

    status_rows = _load_rows(STATUS_JSON, _field_names(StatusSnapshotEntry))
    claim_rows = _load_rows(CLAIM_JSON, _field_names(ClaimLedgerEntry))
    figures = _scan_figures(FIGURE_ROOT)
    outputs = _render_all(status_rows, claim_rows, figures)

    if args.check:
        return _check_outputs(outputs)

    _write_outputs(outputs)
    missing = sum(not bool(row["has_manifest"]) for row in figures)
    print(
        "Generated VER2 export skeleton surfaces "
        f"({len(outputs)} files; {len(figures)} figure bases scanned; "
        f"{missing} missing manifests)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
