"""PR-227: independent reproduction, source audit and publication-grade capsule.

Every Track-I card is regenerated by its own runner and byte-compared against the
committed result card (--check). The capsule records the environment recipe and
pins each card's spec sha. The AUTHOR-side reproduction is verified here; the
Independence gate (a NON-AUTHOR analyst on a clean machine) stays explicitly OPEN
until adjudication capacity returns -- it is never fake-passed.
"""
from __future__ import annotations
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]

# (pr, runner) for every Track-I revival card
RUNNERS = [
    ("PR-209", "run_pr209_inventory.py"),
    ("PR-210", "run_pr210_bundle.py"),
    ("PR-211", "run_pr211_convention.py"),
    ("PR-212", "run_pr212_frame_functor.py"),
    ("PR-213", "run_pr213_claim_state.py"),
    ("PR-214", "run_pr214_mutation_lab.py"),
    ("PR-215", "run_pr215_joint.py"),
    ("PR-216", "run_pr216_ladder.py"),
    ("PR-217", "run_pr217_mes.py"),
    ("PR-218", "run_pr218_surrogate.py"),
    ("PR-219", "run_pr219_quotient.py"),
    ("PR-220", "run_pr220_evidence.py"),
    ("PR-221", "run_pr221_dipole.py"),
    ("PR-222", "run_pr222_bridge.py"),
    ("PR-223", "run_pr223_multifluid.py"),
    ("PR-224", "run_pr224_falsifier.py"),
    ("PR-225", "run_pr225_estcov.py"),
    ("PR-226", "run_pr226_datalane.py"),
]


def reproduce_all() -> dict:
    results = {}
    for pr, runner in RUNNERS:
        path = REPO / "scripts/codex_harness" / runner
        proc = subprocess.run(
            [sys.executable, "-B", str(path), "--check"],
            cwd=REPO, capture_output=True, text=True, timeout=300, check=False,
            env={"PYTHONHASHSEED": "0", "PATH": __import__("os").environ.get("PATH", "")})
        results[pr] = {"runner": runner, "exit": proc.returncode,
                       "byte_stable": proc.returncode == 0}
    all_stable = all(v["byte_stable"] for v in results.values())
    return {"per_card": results, "n_cards": len(RUNNERS),
            "all_byte_stable": all_stable,
            "author_reproduction": "VERIFIED" if all_stable else "FAILED"}


def environment_recipe() -> dict:
    return {
        "python": f"{sys.version_info.major}.{sys.version_info.minor}",
        "data_root_env": "HTT_DATA_ROOT",
        "default_data_root": "/mnt/sn850x2t/htt_base_e2e",
        "cas_engines": ["wolfram_xact", "sympy", "sage_singular", "lean", "rocq"],
        "note": "legacy drop is gitignored; sha-pinned by the PR-209 inventory receipt",
    }
