

# This file was *autogenerated* from the file /home/cosmosapjw/Dropbox/bianchi/htt_base/docs/research_program/gr_statistics_loops_20260930/local_cas/GRSTAT-CAS11-C03-20261001T020800Z/sage_singular/proof.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
from sage.all import *

# Exact polynomial/rational-function certificates. The general-dimensional
# argument, including positivity, is in PROOF.md.
P = PolynomialRing(QQ, names=('w1','w2','w3','b11','b21','b31','b12','b22','b32',
                              'x1','x2','x3','y1','y2','y3',
                              'r11','r21','r31','r12','r22','r32','a1','a2'))
z = P.gens_dict()
F = P.fraction_field()
w1,w2,w3 = (F(z[k]) for k in ('w1','w2','w3'))
B = matrix(F, _sage_const_3 , _sage_const_2 , [z['b11'],z['b12'],z['b21'],z['b22'],z['b31'],z['b32']])
W = diagonal_matrix(F, [w1,w2,w3])
G = B.transpose()*W*B
assert G.det() != _sage_const_0 
Q = B*G.inverse()*B.transpose()*W
assert Q*Q == Q, 'rank-two weighted projection idempotence'
assert B.transpose()*W*(identity_matrix(F,_sage_const_3 )-Q) == _sage_const_0 , 'rank-two weighted orthogonality'
print('SAGE_PROJECTION_RANK2_SYMBOLIC_OK')

x = vector(F, [z['x1'],z['x2'],z['x3']])
y = vector(F, [z['y1'],z['y2'],z['y3']])
ip = lambda u,v: u*W*v
lhs = ip(x,x)*ip(y,y)-ip(x,y)**_sage_const_2 
rhs = sum(W[i,i]*W[j,j]*(x[i]*y[j]-x[j]*y[i])**_sage_const_2 
          for i in range(_sage_const_3 ) for j in range(i+_sage_const_1 ,_sage_const_3 ))
assert lhs == rhs, 'weighted Cauchy-Binet/SOS kernel'
print('SAGE_WEIGHTED_CS_SOS_SYMBOLIC_OK')

Rvec = [vector(F,[z['r11'],z['r21'],z['r31']]),
        vector(F,[z['r12'],z['r22'],z['r32']])]
a = vector(F,[z['a1'],z['a2']])
R = matrix(F,_sage_const_2 ,_sage_const_2 ,lambda i,j: ip(Rvec[i],Rvec[j]))
s = a[_sage_const_0 ]*Rvec[_sage_const_0 ] + a[_sage_const_1 ]*Rvec[_sage_const_1 ]
assert a*R*a == ip(s,s), 'weighted Gram quadratic identity'
assert R.det() == sum(W[i,i]*W[j,j]*(Rvec[_sage_const_0 ][i]*Rvec[_sage_const_1 ][j]-Rvec[_sage_const_0 ][j]*Rvec[_sage_const_1 ][i])**_sage_const_2 
                      for i in range(_sage_const_3 ) for j in range(i+_sage_const_1 ,_sage_const_3 )), 'Gram determinant SOS'
print('SAGE_GRAM_SYMBOLIC_OK')

# Degenerate controls, exact arithmetic.
I = identity_matrix(QQ,_sage_const_3 )
Z = zero_matrix(QQ,_sage_const_3 )
assert Z*Z == Z and I*I == I
assert not [] and sum([],_sage_const_0 ) == _sage_const_0 
assert matrix(QQ,_sage_const_2 ,_sage_const_2 ,[_sage_const_1 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ]).det() == _sage_const_0 
print('SAGE_DEGENERATE_CONTROLS_OK')
print('SAGE_ALL_OK')

